### ISSUE TITLE
IVSHMEM broken on windows 7

### ISSUE THREAD

**Issue by Vaporeon** [duncanthrax/scream#46] opened 2019-05-15 06:46 UTC
I'm sure this is really a bug with Qemu or the IVSHMEM driver, but when drying to use scream on Windows 7, either the OS hangs or I get no audio output. I'm not exactly sure why.

**Comment by martinellimarco** [comment] 2019-05-15 08:46
Hi @Vaporeon 
I remember we discussed this in #36 but I never wrote a follow up. I tested it on Windows 7 and I confirm that the problem is the IVSHMEM driver, as reported also in the issue I mentioned you the last time.
I see that you wrote a message to that issue also. I hope they'll fix it, unfortunately there is nothing I can do in Scream to work around this.
I suggest you use the network version for now, it does work well, expecially if you have a virtio network between host and guest.

I'm closing this since it's not a Scream issue, sorry.

**Closed by martinellimarco** 2019-05-15 08:46 UTC

**Comment by kode54** [comment] 2019-09-29 07:01
I'm having this same problem with Windows 10 1903. IVSHMEM is working for Looking Glass, though.

**Comment by Vaporeon** [comment] 2020-04-21 21:54
This could be fixed by https://github.com/virtio-win/kvm-guest-drivers-windows/pull/445, but there are no signed driver builds.
